load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "zug",
    strip_prefix = "zug-master",
    urls = ["https://github.com/arximboldi/zug/archive/master.tar.gz"],
    # Add the following to avoid security risks.
    # sha256 = "..."
)

load("@zug//bazel:deps.bzl", "zug_deps")

zug_deps()

# zug_deps() will load boost if not already defined in your workspace,
# but the following 2 calls need to be in your WORKSPACE file as well.
load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")

boost_deps()

# Ignore everything below this line if you're a user.

http_archive(
    name = "com_google_googletest",
    sha256 = "66f4362996da6750d1126fc4cff8ebae65ccc07054f5050453f43dd704f5bfcb",
    strip_prefix = "googletest-68ca04c261ded1b936ef5c121618247f7010d445",
    urls = ["https://github.com/google/googletest/archive/68ca04c261ded1b936ef5c121618247f7010d445.tar.gz"],
)
